enum ModalTitles {
    CREATE_APPLICANT = "Create Applicant",
    EDIT_APPLICANT = "Update Applicant",
    APPLICANT_TESTS = "Applicant test data",
    CREATE_FOREIGN_TEST = "Create foreign language test data",
    CREATE_LOGIC_TEST = "Create logic test data",
    CREATE_PROGRAMMING_TEST = "Create programming language test data",
    CREATE_HIRING = "Create a hire",
    HIRING_DATA = "Hiring data",
    HIRING_DESCRIPTION= "Update description",
    HIRING= "Hiring",
    CREATE_EMPLOYEE = "Create Employee",
    EDIT_EMPLOYEE = "Update Employee",
    EMPLOYEE_DATA = "Employee data",
    CREATE_TEMPLATE = "Create Template",
    UPLOAD_TEMPLATE = "Upload Template",
    EDIT_POSITION = "Update Position",
    CREAT_POSITION = "Create Position",
    EDIT_DEPARTMENT = "Update Department",
    CREAT_DEPARTMENT = "Create Department",
    EDIT_FOREIGN_LANGUAGE = "Update Foreign language",
    CREAT_FOREIGN_LANGUAGE = "Create Foreign language",
    EDIT_PROGRAMMING_LANGUAGE = "Update Programming language",
    CREAT_PROGRAMMING_LANGUAGE = "Create Programming language",
    EDIT_USER = "Update User",
}

export default ModalTitles;